{% set name = "terminal-table" %}
{% set version = "3.0.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 9273aff0bfab536c05fdf2e301b760326d3b8c4575ada987843a82828eaecb7c

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-unicode-display_width >=1.1.1,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Simple, feature rich ascii table generation library

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/tj/terminal-table

extra:
  recipe-maintainers:
    - sodre
