travis:
  secure:
    BINSTAR_TOKEN: uBULYgZ+o//hi/aRxwNayeZLcl/7n5Cii9RGKxscOkrOKmRmo0obFRcDHAqbQ1iaVCKHxbjy+VDD3qVMyJDaKs8fR3ZxocRKpb3n+04WQ+uOa59HSovTG+sdGpd00M29Vx3nRSk1J8hMAt1qo3Sd5vmb++Yi7KAx9VaAFjzNwII+/mLy97qfwHZh37MrxfiVSZmXXJSQnFiUM9TSDJvsyREyfmgeRbzbv2Qke28nw9tdGVc9jRPDwELQDrp6vkk2+bKnW/ymy7z+t9UAajvlyMPRuWGxJQ3ae+SLVftXfA9imQyz6MfTu1YtVmW+1SyYG16Syu2AZqw00AkUlkH4dQ7uxhGkl2gDtxl+sYL0HfvaskXIvivCSnE01e462ruV3ksiLjkgHol1JhBVTaZETgkarY7EUWAeb5nnMRxmgSInQly2rLIFzVQLJUH2PpLcIzC6yVbCcK516thktvD/DM+nE6+71kC6eOAZDmKyIUULxX1yXEw39gnW7gg09TF3VQNqqJ1uN4+O5fbB6RxkSZcv1psyliigHRzRd8GUTsAHSE+pXy9qfdTC1ItVcDUANNi46nim3MqfNgSJnFSwNj9aHTkcknqiJzlXwAYmxcljc7w796Nzo8XHdqt5Q84KRMSsgspXUTWEWtcqfgRU+/ZcSSfTfY5GeqyA7Wh5ubs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
